blank_issues_enabled: false
contact_links:
  - name: Discuss Wonders on the Discord server.
    url: https://debuggy.gay/discord
    about: Discuss bug reports, suggestions or other Wonders related stuff on our Discord server.
