blank_issues_enabled: false
contact_links:
  - name: Discuss Wonders on the Discord server.
    url: https://discord.gg/SN89y7EQTN
    about: Discuss bug reports, suggestions or other Wonders related stuff on our Discord server.
